apiVersion: v2
name: openldap-stack-ha
dependencies:
  - name: ltb-passwd
    version: 0.1.x
    condition: ltb-passwd.enabled
  - name: phpldapadmin
    version: 0.1.x
    condition: phpldapadmin.enabled
home: https://www.openldap.org
version: 2.1.5
appVersion: 2.4.57
description: Community developed LDAP software
icon: https://raw.githubusercontent.com/djtalez/helm-openldap/master/logo.png
keywords:
  - ldap
  - openldap
  - iam-stack
  - high availability 
sources:
  - https://github.com/djtalez/helm-openldap
maintainers:
  - name: Toons
    email: djtalez@gmail.com
engine: gotpl
